# Render部署配置文件
services:
  - type: web
    name: xmind-mcp-server
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    buildCommand: ""
    startCommand: "python xmind_mcp_server.py"
    plan: free # 使用免费层
    autoDeploy: true # 自动部署